[project]
<<<<<<< Updated upstream
name = "ps2-new"
=======
name = "backend"
>>>>>>> Stashed changes
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
<<<<<<< Updated upstream
    "pymupdf>=1.26.1",
    "requests>=2.32.4",
=======
    "fastapi>=0.116.1",
    "groq>=0.30.0",
    "nltk>=3.9.1",
    "numpy>=2.3.1",
    "pypdf2>=3.0.1",
    "python-docx>=1.2.0",
    "python-dotenv>=1.1.1",
    "python-multipart>=0.0.20",
    "scikit-learn>=1.7.0",
    "sentence-transformers>=5.0.0",
    "uvicorn>=0.35.0",
>>>>>>> Stashed changes
]
